services:
  master:
    build:
      context: ./master
    container_name: lab2-master
    environment:
      NODE_NAME: master
      REPLICA_URLS: http://replica-1:8100,http://replica-2:8100
    ports:
      - "8102:8100"
    depends_on:
      - replica-1
      - replica-2

  replica-1:
    build:
      context: ./replica
    container_name: lab2-replica-1
    environment:
      NODE_NAME: replica-1
    ports:
      - "8103:8100"

  replica-2:
    build:
      context: ./replica
    container_name: lab2-replica-2
    environment:
      NODE_NAME: replica-2
    ports:
      - "8104:8100"
